"""Deterministic billing and calculation service (FR-014, FR-018).

Ensures all arithmetic is computed by backend rules, never generated by the LLM.
"""

from orca.domain.schemas import BillSummary
from orca.core.regional import get_regional_profile


class BillingService:
    """Computes exact transaction amounts, taxes, and bills."""

    @staticmethod
    def calculate_bill(
        produce_type: str,
        quantity: float,
        unit: str,
        rate_per_unit: float,
        region_code: str = "GLOBAL_DEFAULT",
    ) -> BillSummary:
        """Calculate total amount and tax deterministically.

        FR-014: The backend shall calculate total amount from validated quantity, unit and rate.
        """
        profile = get_regional_profile(region_code)
        subtotal = round(quantity * rate_per_unit, 2)
        tax_amount = round(subtotal * (profile.tax_rate_percentage / 100.0), 2)
        total_amount = round(subtotal + tax_amount, 2)

        return BillSummary(
            produce_type=produce_type,
            quantity=quantity,
            unit=unit,
            rate_per_unit=rate_per_unit,
            currency=profile.currency_code,
            subtotal=subtotal,
            tax_amount=tax_amount,
            total_amount=total_amount,
        )


billing_service = BillingService()
