"""Procurement domain contracts, policy configuration, and evaluation schemas.

Implements SRS Section 13 & Procurement Intelligence Layer:
- Configuration-driven ProcurementConstraints (min/max qty, advance horizon, allowed units)
- Authoritative ProcurementEvaluation DTO
- In-memory FutureHarvestDeclaration for staged/partial availability
"""

from datetime import datetime, timezone, timedelta
from typing import Dict, List, Optional
from pydantic import BaseModel, Field

from orca.domain.models import Rate
from orca.domain.schemas import BillSummary, ExtractedOffer


class ProcurementConstraints(BaseModel):
    """Configuration/policy-driven constraints for evaluating agricultural produce offers.
    
    CRITICAL: These thresholds are configuration/policy driven and must NOT become
    universal hard-coded truths. They can be scoped by region, commodity, or buyer profile.
    """

    policy_id: str = "GLOBAL_DEFAULT_POLICY"
    region_code: str = "GLOBAL_DEFAULT"
    produce_type: Optional[str] = None  # None indicates general default for the region
    min_quantity: float = 5.0
    max_quantity: float = 10000.0
    allowed_units: List[str] = Field(
        default_factory=lambda: ["kg", "quintal", "ton", "lb", "bag"]
    )
    max_advance_days: int = 14
    min_advance_hours: float = 2.0
    allow_partial_lots: bool = True
    fixed_rate_policy_message: str = (
        "ORCA procurement operates on authoritative fixed market purchase rates. "
        "We provide guaranteed farm-gate collection by a local runner, zero middleman "
        "deductions, and immediate verified electronic payout."
    )

    def validate_constraints(
        self,
        quantity: Optional[float],
        unit: Optional[str],
        pickup_datetime: Optional[datetime] = None,
        now: Optional[datetime] = None,
    ) -> List[str]:
        """Evaluate quantity, unit, and scheduling against this policy.
        
        Returns a list of violation codes (empty if fully valid).
        """
        violations: List[str] = []

        # 1. Quantity checks
        if quantity is not None:
            if quantity <= 0:
                violations.append("QUANTITY_NON_POSITIVE")
            elif quantity < self.min_quantity:
                violations.append(f"QUANTITY_BELOW_MINIMUM:{self.min_quantity}")
            elif quantity > self.max_quantity:
                violations.append(f"QUANTITY_EXCEEDS_MAXIMUM:{self.max_quantity}")

        # 2. Unit checks
        if unit:
            normalized_allowed = [u.lower() for u in self.allowed_units]
            if unit.lower() not in normalized_allowed:
                violations.append(f"UNSUPPORTED_UNIT:{unit}")

        # 3. Timing / Scheduling checks
        if pickup_datetime:
            current_time = now or datetime.now(timezone.utc)
            if pickup_datetime.tzinfo is None:
                # Assume UTC if naive for testing
                pickup_dt_utc = pickup_datetime.replace(tzinfo=timezone.utc)
            else:
                pickup_dt_utc = pickup_datetime

            if current_time.tzinfo is None:
                current_time = current_time.replace(tzinfo=timezone.utc)

            # Check if in past
            if pickup_dt_utc < current_time - timedelta(minutes=15):
                violations.append("SCHEDULE_IN_PAST")

            # Check advance horizon
            max_future = current_time + timedelta(days=self.max_advance_days)
            if pickup_dt_utc > max_future:
                violations.append(f"SCHEDULE_EXCEEDS_MAX_ADVANCE:{self.max_advance_days}_DAYS")

        return violations


class ProcurementEvaluation(BaseModel):
    """Authoritative evaluation result of a produce offer against procurement policy.
    
    Purely deterministic assessment generated by backend services.
    The LLM never generates or alters this evaluation.
    """

    is_acceptable: bool = False
    produce_supported: bool = False
    rate: Optional[Rate] = None
    bill_summary: Optional[BillSummary] = None
    missing_fields: List[str] = Field(default_factory=list)
    rejection_reasons: List[str] = Field(default_factory=list)
    pricing_discrepancy: bool = False
    farmer_offered_rate: Optional[float] = None
    authoritative_rate: Optional[float] = None
    quantity_within_limits: bool = True
    timing_within_limits: bool = True
    guidance_message: Optional[str] = None
    policy_id: str = "GLOBAL_DEFAULT_POLICY"
    evaluated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class FutureHarvestDeclaration(BaseModel):
    """In-memory representation of partial or future harvest availability.
    
    Observational conversational context only; does not create an unconfirmed order.
    """

    produce_type: Optional[str] = None
    future_quantity: Optional[float] = None
    unit: Optional[str] = None
    estimated_window: Optional[str] = None
    notes: Optional[str] = None
    declared_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# =============================================================================
# Policy Configuration Registry
# =============================================================================

# Pre-configured baseline policies
_PROCUREMENT_POLICIES: Dict[str, ProcurementConstraints] = {
    "GLOBAL_DEFAULT": ProcurementConstraints(
        policy_id="GLOBAL_DEFAULT_POLICY",
        region_code="GLOBAL_DEFAULT",
        min_quantity=5.0,
        max_quantity=10000.0,
        allowed_units=["kg", "quintal", "ton", "lb", "bag"],
        max_advance_days=14,
        min_advance_hours=2.0,
    ),
    "US_STANDARD": ProcurementConstraints(
        policy_id="US_STANDARD_POLICY",
        region_code="US_STANDARD",
        min_quantity=10.0,
        max_quantity=20000.0,
        allowed_units=["lb", "ton", "kg"],
        max_advance_days=14,
        min_advance_hours=3.0,
    ),
    "IN_MH": ProcurementConstraints(
        policy_id="IN_MH_POLICY",
        region_code="IN_MH",
        min_quantity=10.0,
        max_quantity=15000.0,
        allowed_units=["kg", "quintal", "ton"],
        max_advance_days=10,
        min_advance_hours=2.0,
    ),
    "KE_RV": ProcurementConstraints(
        policy_id="KE_RV_POLICY",
        region_code="KE_RV",
        min_quantity=5.0,
        max_quantity=10000.0,
        allowed_units=["kg", "bag", "ton"],
        max_advance_days=14,
        min_advance_hours=2.0,
    ),
}


def get_procurement_policy(
    region_code: str = "GLOBAL_DEFAULT",
    produce_type: Optional[str] = None,
) -> ProcurementConstraints:
    """Retrieve active procurement policy with hierarchical fallback:
    
    1. Specific {region_code}:{produce_type}
    2. Specific {region_code}
    3. GLOBAL_DEFAULT fallback
    """
    if produce_type:
        key_commodity = f"{region_code}:{produce_type.strip().lower()}"
        if key_commodity in _PROCUREMENT_POLICIES:
            return _PROCUREMENT_POLICIES[key_commodity]

    if region_code in _PROCUREMENT_POLICIES:
        return _PROCUREMENT_POLICIES[region_code]

    return _PROCUREMENT_POLICIES["GLOBAL_DEFAULT"]


def register_procurement_policy(policy: ProcurementConstraints) -> None:
    """Register or override a procurement policy dynamically (for test/admin configuration)."""
    if policy.produce_type:
        key = f"{policy.region_code}:{policy.produce_type.strip().lower()}"
    else:
        key = policy.region_code
    _PROCUREMENT_POLICIES[key] = policy
